### ISSUE TITLE
Mangled markdown formatting for a list with indented items

### ISSUE THREAD

**Issue by jasonkuhrt** [homer0/packages#21]
Before format, the Goal:

<img width="1266" alt="CleanShot 2021-08-30 at 13 40 53@2x" src="https://user-images.githubusercontent.com/284476/131381768-b572f125-8ddf-4db6-9184-cf7f46f6df9f.png">

<img width="996" alt="CleanShot 2021-08-30 at 13 41 03@2x" src="https://user-images.githubusercontent.com/284476/131381773-afbb2c0f-0028-4c38-8a10-12d3e233aafc.png">

After format, not desired result:

<img width="999" alt="CleanShot 2021-08-30 at 13 41 11@2x" src="https://user-images.githubusercontent.com/284476/131381812-291b7062-ddd5-4232-be22-1414bf345f24.png">

<img width="996" alt="CleanShot 2021-08-30 at 13 41 19@2x" src="https://user-images.githubusercontent.com/284476/131381818-3c7fcf41-47e5-4581-80b5-577f0ddae1c2.png">

**Comment by homer0** [comment]
@jasonkuhrt Hey 👋 !

Sorry, but I don't see this happening anytime soon; indentation is something that gets completely removed and ignored while parsing the lines, and calculating the sentence's "break" to accommodate the `printWidth`. Adding that kind of support would mean rewriting a LOT of stuff.

Now, looking at your example, I would say you are using the plugin just for the `printWidth` there, and I would suggest you to add the `@prettierignore` tag and handle it manually.

I'm sorry I can't be of much help with this, but to be honest, the support for basic markdown styling was a happy accident, and supporting markdown completely is way out of scope for the plugin.
