### ISSUE TITLE
prettier jsdoc: Incorrect newline insertion

### ISSUE THREAD

**Issue by wmertens** [homer0/packages#24]
(shortened for repro)
```js
/**
 * @template {InputProps<Value>} [Props=React.ComponentProps<Input>]
 */
```

becomes
```js
/**
 * @template {InputProps<Value>}
 * [Props=React.ComponentProps<Input>]
 */
```

which is no longer a valid template definition for Props :-(

Oddly enough, in another place it doesn't insert a newline ?-|

```js
/**
 * @type {React.FunctionComponent<
 * 	LayoutProps & {Input: Input; inputProps?: Partial<Props>} & Props
 * >}
 * @template {InputComponent<Props, Value>} Input
 * @template {InputProps<Value>} [Props=React.ComponentProps<Input>]
 * @template [Value=Props['value']]
 */
```

**Comment by wmertens** [comment]
This even happens when I shorten everything?

```js
const StyledInputLayout = /**
 * @type {import('styled-components').ThemedStyledFunction<
 * 		InputLayout<Input, Props, Value>
 * 	>}
 * @template {InputComponent<P, V>} I
 * @template {InputProps<V>} [P=React.ComponentProps<I>]
 * @template [V=P['value']]
 * @template [IL=InputLayout<I,P,V>]
 */ (styled(InputLayout)).attrs(p => ({
	labelOnTop: p.inline
		? false
		: p.labelOnTop == null
		? p.theme.labelTop
		: p.labelOnTop,
}))``
```

**Comment by homer0** [comment]
I can't reproduce it, but as an action for the issue, I write down a PR template with indications on how to create a `fixture` to validate problems.

I know it's not the solution you are looking for, but debugging it will be faster than trying to reproduce it based on the issue, plus, we can know if it's config related, or code related.

**Comment by homer0** [comment]
Hi @wmertens 👋 !

In the [plugin's `README`](https://github.com/homer0/packages/tree/main/packages/public/prettier-plugin-jsdoc#-validating-bugs), I added a way to validate the bugs.

Since I couldn't reproduce it, could you generate a fixture for it?

**Comment by wmertens** [comment]
Ok thank you, I'll take a look!

**Comment by wmertens** [comment]
To reproduce I had to reduce prettier's `printWidth`, which is odd because I don't do that in my code.

https://github.com/homer0/packages/compare/main...wmertens:asterisks

**Comment by homer0** [comment]
@wmertens Hey 👋 

I found a bug on how the rendering was being decided, more info on #43, but since even with REALLY small `printWidth`, `@template` still needs to be in a single line to be detected by the `tsc`, I added a constant, so the plugin will never try to put it in multiple lines.

Let me know how it goes!
