### ISSUE TITLE
jsdoc: incorrect sorting of typedefs

### ISSUE THREAD

**Issue by wmertens** [homer0/packages#3]
```diff
 /**
   * @typedef {Object} SPContext
-  * @prop {PnpWeb} web
-  * @prop {PnpList} spList
-  * @prop {number} spListId
-  * @prop {Models} models
-  * @typedef {PnpItem & {File?: *, Folder?: *}} SPDetail
+  * @typedef {PnpItem & {File?: any; Folder?: any}} SPDetail
+  * @property {PnpWeb} web
+  * @property {PnpList} spList
+  * @property {number} spListId
+  * @property {Models} models
 */
```

It shouldn't have moved the second typedef before the props...

**Comment by homer0** [comment]
@wmertens I'm so sorry! There's something wrong with my notifications; I'm watching all activity on the repository, but I never got an email about this.

I'll be checking the issue and the PR between today and tomorrow.

**Comment by wmertens** [comment]
No problem, and thanks for your awesome plugin, it makes typing in plain js so much better, because you can see mistakes due to the code not formatting.

**Comment by homer0** [comment]
Hey! Thank you for the kind words :D!

Now you are probably going to hate me :P : unfortunately, it's intended to work like that.

The sorting functionality doesn't understand how some tags play together, it simply takes a list of tags and a reference list and makes sure the tags respect the priority of the reference list:

```js
/**
 * Creates the function used by `Array.sort` to actually sort the tags based on a
 * reference list.
 *
 * @param {string[]} ref  The reference list with the order for the tags.
 * @returns {Function}
 */
const createSorter = (ref) => {
  const useGetIndexOrFallback = get(getIndexOrFallback);
  const fallback = useGetIndexOrFallback(ref, ref.length, 'other');
  const getTagWeight = useGetIndexOrFallback(ref, fallback);
  return (a, b) => getTagWeight(a.tag) - getTagWeight(b.tag);
};
```

That logic would get a little bit more complex if I were to add checks like "but there's another typedef on this block? Does it have properties? Which properties correspond to which typedef", when the alternative is as simple as creating two blocks (2 or 3 extra lines):

```diff
 /**
  * @typedef {Object} SPContext
  * @prop {PnpWeb} web
  * @prop {PnpList} spList
  * @prop {number} spListId
  * @prop {Models} models
+ */
+/**
  * @typedef {PnpItem & {File?: *, Folder?: *}} SPDetail
  */
```

Now, if you think there's a way to do it, generic enough that can be configured, I would gladly accept a PR, review it and help you if you need it, but having such a simple workaround, I can't give it priority, sorry 🙏!

Btw, I'll check the notifications' configuration right now, so I won't miss other issues/PRs.

Regards

**Comment by wmertens** [comment]
Ok makes sense, I'll close this for now
