### ISSUE TITLE
Conflict with `@trivago/prettier-plugin-sort-imports` plugin

### ISSUE THREAD

**Issue by KarimTayel** [homer0/packages#55]
Hi,

I tried to use `@homer0/prettier-plugin-jsdoc` plugin and it didn't work.

I have other prettier plugins installed:

```javascript
module.exports = {
  plugins: [
      '@homer0/prettier-plugin-jsdoc',
      '@trivago/prettier-plugin-sort-imports',
      'prettier-plugin-organize-attributes',
      'prettier-plugin-packagejson',
  ]
}
```
So I tried to disable these plugins one by one and test if it's working and it seems there is some kind of conflict with [`@trivago/prettier-plugin-sort-imports`](https://github.com/trivago/prettier-plugin-sort-imports) plugin.

**Comment by homer0** [comment]
@KarimTayel 👋 I'll try to take a look this weekend.

**Comment by benediktms** [comment]
Hi, I'm running into the exact same issue. with [@trivago/prettier-plugin-sort-imports](https://github.com/trivago/prettier-plugin-sort-imports) the features I've tested do not seem to work.

**Comment by homer0** [comment]
@KarimTayel @benediktms Sorry for the delay on this!

Seems like it's a bug on Prettier: prettier/prettier#12807

One of the latest comments mentions a workaround posted in tailwind plugin:

```js
// .prettierrc.js

const pluginSortImports = require("@trivago/prettier-plugin-sort-imports");
const pluginJSDoc = require("@homer0/prettier-plugin-jsdoc");

/**
 * @type {import('prettier').Parser}
 */
const myParser = {
  ...pluginSortImports.parsers.babel,
  parse: pluginJSDoc.parsers.babel.parse,
};

console.log(myParser);

/**
 * @type {import('prettier').Plugin}
 */
const myPlugin = {
  parsers: {
    babel: myParser,
  },
};

module.exports = {
  plugins: [myPlugin],
};
```
> _[Original comment](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/31#issuecomment-1195411734)_.

Sorry it couldn't be fixed from this side.
