### ISSUE TITLE
prettier jsdoc: property names containing apostrophe should stay in double quotes in complex type definitions

### ISSUE THREAD

**Issue by anantakrishna** [homer0/packages#58]
Input:

```
/**
 * @typedef {{
 *   'Sr No': number;
 *   'Program name': string;
 *   Seniority: number | null;
 *   "Speaker's name": string;
 * }} MemoriesRow
 */
```

The `Speaker's name` property contains apostrophe, hence double quotes should be used around it. But currently (plugin v5.1.5) the output is invalid. First double quote is replaced with an apostrophe, space is added after the existing apostrophe:

```
/**
 * @typedef {{
 *   'Sr No': number;
 *   'Program name': string;
 *   Seniority: number | null;
 *   'Speaker' s name": string;
 * }} MemoriesRow
 */
```

**Comment by homer0** [comment]
Hi @anantakrishna!

Sorry for the delay, but I just released the fix, and added a test case in the repo with your snippet.

Regards
