### ISSUE TITLE
prettier jsdoc: incorrect wrapping in long `typedef`

### ISSUE THREAD

**Issue by anantakrishna** [homer0/packages#59]
Input:

```
/**
 * @typedef {import('./MemoriesAlgoliaRecord').MemoriesAlgoliaRecord} MemoriesAlgoliaRecord
 */
```

Output:

```
/**
 * @typedef {import('./MemoriesAlgoliaRecord').MemoriesAlgoliaRecord}
 * MemoriesAlgoliaRecord
 */
```
which technically seemS to work, but VSCode highlights `MemoriesAlgoliaRecord` as comment, not a type name. Moreover, next formatting completely breaks it:

```
/**
 * MemoriesAlgoliaRecord.
 *
 * @typedef {import('./MemoriesAlgoliaRecord').MemoriesAlgoliaRecord}
 */
```

Plugin version: 5.1.5

**Comment by homer0** [comment]
Hi @anantakrishna!

Sorry for the delay, but I just released the fix, and added a test case in the repo with your snippet.

Regards
