### ISSUE TITLE
Mangling of markdown tables

### ISSUE THREAD

**Issue by jasonkuhrt** [homer0/packages#7]
Before:

<img width="963" alt="Screen Shot 2021-03-09 at 2 53 56 PM" src="https://user-images.githubusercontent.com/284476/110529542-624dd200-80e7-11eb-8c94-a747b71f2c64.png">

After:

<img width="902" alt="Screen Shot 2021-03-09 at 2 54 01 PM" src="https://user-images.githubusercontent.com/284476/110529544-624dd200-80e7-11eb-898d-691a425aa32b.png">

- Not sure why the first one is left untouched.
- Not sure why a period was added to the first one (I didn't do that).
- The second one gets mangled and then breaks rendering.

**Comment by homer0** [comment]
Damn; that's a bug - the most complex cases I tried for the descriptions were lists, so it's probably parsing it as text and "closing the sentence before the line break" (the period) :P.

I'll try to check it this week.
