### ISSUE TITLE
Markdown lists get squished

### ISSUE THREAD

**Issue by wmertens** [homer0/packages#71]
I have `"jsdocExperimentalFormatCommentsWithoutTags": true` if that makes any difference

```
/**
 * Foo
 *
 * - hi
 * - there.
 */
```

becomes
```
/**
 * Foo
 *
 * - hi - there.
 */
```

Would it be possible to retain the markdown formatting?

Thanks once again for your awesome plugin :heart:

**Comment by homer0** [comment]
@wmertens as always, sorry for the delay 😞

Try adding a period after `hi`. The formatter doesn't recognize markdown, but if it detects a period, it won't try to join the lines:

https://github.com/homer0/packages/assets/6949310/d4bc32ad-d5b7-4d02-a755-96bf9d7676f6

**Comment by wmertens** [comment]
Thanks! I thought it considered comments as markdown 😅
