### ISSUE TITLE
@homer0/prettier-plugin-jsdoc@6.0.5: shebang is removed with prettier@3.0.0

### ISSUE THREAD

**Issue by campersau** [homer0/packages#73]
Steps to reproduce in a empty folder run:

```
npm install prettier@3.0.0
```
```
npm install @homer0/prettier-plugin-jsdoc@6.0.5
```

Create index.js with the following content:
```js
#!/usr/bin/env node
console.log("hello world");
```

Running just `prettier` returns the correct result:
```
npx prettier index.js
```

```js
#!/usr/bin/env node
console.log("hello world");
```

Running with `@homer0/prettier-plugin-jsdoc` removes the shebang:
```
npx prettier --plugin "@homer0/prettier-plugin-jsdoc" index.js 
```

```js
console.log("hello world");
```

Not sure if this is a bug in `@homer0/prettier-plugin-jsdoc` or in `prettier`.
It works when using `prettier@2.8.8`.

---

Tested also other plugins like `@prettier/plugin-php@0.19.6` where this works correctly with both versions of `prettier`.

**Comment by homer0** [comment]
@campersau Hey 👋 

I wasn't aware that Prettier 3 was out! I'll check this today, regardless which package cause the issue, it should be an easy fix.

**Comment by homer0** [comment]
@campersau 👋 

It took more than I expected, but after adding support for V3, it seems like the shebang issue is gone. I added a test for it, and, just in case, here's a video:


https://github.com/homer0/packages/assets/6949310/11b4a3f8-c16d-4585-b608-d97eb98a412f

Have fun!
