### ISSUE TITLE
Strange rendering of remarks

### ISSUE THREAD

**Issue by jasonkuhrt** [homer0/packages#8]
![image](https://user-images.githubusercontent.com/284476/110529932-d7b9a280-80e7-11eb-813c-8dc3e51ee34c.png)

Maybe I'm missing something but that seems off. Why the double space after the first word. Is that being treated as some kind of keyword? I'm using remarks as [it was specified in TSDoc](https://tsdoc.org/pages/tags/remarks/).

**Comment by homer0** [comment]
Hi @jasonkuhrt !

Sorry for the delay! This doesn't follow TSDoc, but [JSDoc](https://jsdoc.app) so don't expect all the tags from TSDoc to work out of the box.

Now, this is a really easy fix; for tags like this one, where there's no "type" nor "name", the comments' parser takes the first word as the "name". I'll just configure the plugin, so it will handle it the same way it handles `@see` or `@license`.

I'll try to push the fix today.

Btw, let me know if you see other issues with TSDoc, I'm not against adding compatibility, but I don't have time right now to go and do a full research :P.

Regards.

**Comment by jasonkuhrt** [comment]
Awesome thanks! And will do.
