### ISSUE TITLE
Security Issue in Object-utils package

### ISSUE THREAD

**Issue by xclow3n** [homer0/packages#84]
Hello,

I've identified a vulnerability related to prototype pollution within this package. This issue potentially allows a malicious actor to affect the entire application, manipulate its flow, and, in some scenarios, even achieve code execution. Given that this repository contains personal packages, I was uncertain about the best course of action regarding reporting this issue.

Could you please provide an email address or Discord handle where I can share the details securely? 

Thank you for your attention to this matter.

**Comment by homer0** [comment]
Hi 👋 

Interesting; you can share the details in here, and I'll try to address the issue.

Thanks!

**Comment by xclow3n** [comment]
so apparently the `unflat` is vulnerable to prototype pollution bug, lets take this code for example

```
import { unflat } from '@homer0/object-utils';

const target = { 'propOne.propOneSub': 'Charito!', propTwo: '!!!', '__proto__.xx': 'yes' };
console.log(Object.xx)
var result = unflat({ target })
console.log(Object.xx)
```

If you run this, you will get this out 

```
undefined
yes
```

So basically when the application `unflat` the data it allows attacker to pollute the `Object` using the `prototype` which can also allow attacker to get code execution in some cases

**Comment by homer0** [comment]
Hey 👋,

Thanks a lot for reporting it! Seems like the issue was in the `set` function. I pushed a fix for `__proto__`, `prototype` and `constructor` (those two just in case) and added a few tests to validate it.

I didn't think about it while writing the code, it's the first time someone reports something like this (*), but next time I update the repo, I'll add a comment somewhere in the package linking to your profile for discovering the issue, sorry!

> *: Normally, just me and my friends use my packages :P

**Comment by xclow3n** [comment]
Hello,

Thank you very much! While exploring, I discovered a potential security issue within your package and thought it was important to report it, in case it affects other users as well. 😊 I hope you don't mind, but I'm considering submitting this bug for a CVE (Common Vulnerabilities and Exposures) identification to ensure it's officially recognized and addressed. Would that be alright with you?

Best regards,
